# Generated by Django 5.0 on 2024-05-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pdv_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Allergene',
                'verbose_name_plural': 'Allergeni',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contatto')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantità disponibile')),
                ('unit', models.CharField(choices=[('kg', 'Kilogrammi'), ('unit', 'Unità')], default='unit', max_length=10, verbose_name='Unità di misura')),
                ('allergens', models.ManyToManyField(blank=True, to='inventory.allergen', verbose_name='Allergeni')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv_management.pdv', verbose_name='PDV')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredienti',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='Procedimento')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv_management.pdv', verbose_name='PDV')),
            ],
            options={
                'verbose_name': 'Preparazione',
                'verbose_name_plural': 'Preparazioni',
            },
        ),
        migrations.CreateModel(
            name='PreparationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantità')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.preparation')),
            ],
            options={
                'verbose_name': 'Quantità Ingrediente',
                'verbose_name_plural': 'Quantità Ingredienti',
            },
        ),
        migrations.AddField(
            model_name='preparation',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.PreparationIngredient', to='inventory.ingredient'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo unitario')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantità')),
                ('purchase_date', models.DateField(verbose_name='Data acquisto')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'item')), models.Q(('app_label', 'inventory'), ('model', 'ingredient')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Acquisto',
                'verbose_name_plural': 'Acquisti',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantità disponibile')),
                ('unit', models.CharField(choices=[('kg', 'Kilogrammi'), ('unit', 'Unità')], default='unit', max_length=10, verbose_name='Unità di misura')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv_management.pdv', verbose_name='PDV')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
    ]
